accounts/urls.py
# # accounts/urls.py
# from django.urls import path
# from .views import SignUpView, CustomLoginView ,activate_account, activation_sent , resend_activation_email
# from django.contrib.auth.views import LogoutView
#
# urlpatterns = [
#     path('signup/', SignUpView.as_view(), name='signup'),
#     path('login/', CustomLoginView.as_view(), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
#     path('activation-sent/', activation_sent, name='activation_sent'),
#     path('activate/<uidb64>/<token>/', activate_account, name='activate'),
#     path('resend/', resend_activation_email, name='resend_activation'),
#
# ]
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    SignUpView,
    CustomLoginView,
    activate_account,
    activation_sent,
    resend_activation_email,
    ProfileView,
    EditProfileView,
    delete_account_view
)

urlpatterns = [
    # Authentication URLs
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Account Activation URLs
    path('activation-sent/', activation_sent, name='activation_sent'),
    path('activate/<uidb64>/<token>/', activate_account, name='activate'),
    path('resend/', resend_activation_email, name='resend_activation'),

    # Profile URLs
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('profile/delete/', delete_account_view, name='delete_account'),
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import home  # import the home view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
# from django.urls import path
# from . import views
#
# urlpatterns = [
#     path('register/', views.register, name='register'),
#     path('login/', views.login_view, name='login'),
#     path('profile/', views.user_profile, name='user_profile'),
#     path('profile/edit/', views.edit_profile, name='edit_profile'),
#     path('profile/delete/', views.delete_account, name='delete_account'),
#     path('', views.home, name='home'),
#     path('create_profile/', views.create_profile, name='create_profile'),
#
# ]
#
#
# user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('logout/', views.logout_view, name='logout'),
    path('delete-account/', views.delete_account, name='delete_account'),
]

accounts/models.py
# from django.contrib.auth.models import AbstractUser
# from django.core.validators import RegexValidator
# from django.db import models
#
# class CustomUser(AbstractUser):
#     email = models.EmailField(unique=True)
#     is_active = models.BooleanField(default=False)
#     phone_regex = RegexValidator(
#         regex=r'^01[0125][0-9]{8}$',
#         message="Phone number must be an Egyptian number starting with 010, 011, 012, or 015."
#     )
#     mobile = models.CharField(validators=[phone_regex], max_length=11, blank=True)
#     profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
#
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['first_name', 'last_name']
#
#
# accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=False)
    phone_regex = RegexValidator(
        regex=r'^01[0125][0-9]{8}$',
        message="Phone number must be an Egyptian number starting with 010, 011, 012, or 015."
    )
    mobile = models.CharField(validators=[phone_regex], max_length=11, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True,default='')

    # Add the new optional fields
    birthdate = models.DateField(null=True, blank=True)
    facebook_profile = models.URLField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.email})"

accounts/forms.py
# # accounts/forms.py
# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from .models import CustomUser
# from django.contrib.auth.forms import AuthenticationForm
#
#
# class SignUpForm(UserCreationForm):
#     class Meta:
#         model = CustomUser
#         fields = ['first_name', 'last_name', 'email', 'mobile', 'profile_picture', 'password1', 'password2']
#
# class EmailLoginForm(AuthenticationForm):
#     username = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'autofocus': True}))

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm
from .models import CustomUser
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'mobile', 'profile_picture', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add Bootstrap classes to form fields
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control-file'})


class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(
        label=_("Email"),
        widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control'})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


class UserProfileForm(UserChangeForm):
    password = None  # Remove password field from the form

    birthdate = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
    )
    facebook_profile = forms.URLField(
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-control'}),
    )
    country = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = CustomUser
        fields = [
            'first_name',
            'last_name',
            'mobile',
            'profile_picture',
            'birthdate',
            'facebook_profile',
            'country'
        ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_picture': forms.FileInput(attrs={'class': 'form-control-file'}),
        }


class DeleteAccountForm(forms.Form):
    password = forms.CharField(
        label=_("Confirm your password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not self.user.check_password(password):
            raise ValidationError(_("Incorrect password"))
        return password


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control'}),
    )

accounts/views.py
# # accounts/views.py
# from django.views.generic.edit import CreateView
# from django.contrib.auth.views import LoginView
# from django.urls import reverse_lazy
# from django.utils.http import urlsafe_base64_encode
# from django.utils.encoding import force_bytes
# from django.contrib.sites.shortcuts import get_current_site
# from django.template.loader import render_to_string
# from django.contrib.auth.tokens import default_token_generator
# from django.core.mail import send_mail
# from django.shortcuts import redirect
# from django.contrib import messages
# from .forms import SignUpForm, EmailLoginForm
# from .models import CustomUser
# #>>>>>>>>>>>
# from django.utils.http import urlsafe_base64_decode
# from django.contrib.auth import get_user_model
# from django.contrib.auth.tokens import default_token_generator
# from django.http import HttpResponse
# from django.shortcuts import render
# #.......
# from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
#
#
# class SignUpView(CreateView):
#     model = CustomUser
#     form_class = SignUpForm
#     template_name = 'accounts/signup.html'
#     success_url = reverse_lazy('login')
#
#     def form_valid(self, form):
#         user = form.save(commit=False)
#         # If username is not provided, set it to user's email to ensure uniqueness.
#         if not user.username:
#             user.username = user.email
#         user.is_active = False  # deactivate the user until email is verified
#         user.save()
#
#         # Prepare activation email
#         current_site = get_current_site(self.request)
#         subject = 'Activate your account'
#         message = render_to_string('accounts/account_activation_email.html', {
#             'user': user,
#             'domain': current_site.domain,
#             'uid': urlsafe_base64_encode(force_bytes(user.pk)),
#             'token': default_token_generator.make_token(user),
#         })
#
#         user.email_user(subject, message)
#         messages.success(self.request, 'Check your email to activate your account.')
#         return redirect('login')
#
#
# def activate_account(request, uidb64, token):
#     try:
#         uid = urlsafe_base64_decode(uidb64).decode()
#         user = get_user_model().objects.get(pk=uid)
#     except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
#         user = None
#
#     if user is not None and default_token_generator.check_token(user, token):
#         user.is_active = True
#         user.save()
#         return HttpResponse('Your account has been activated. You can now <a href="/accounts/login/">login</a>.')
#     else:
#         return render(request, 'accounts/activation_invalid.html')
#
#
#
# def activation_sent(request):
#     return render(request, 'accounts/activation_sent.html')
#
#
#
# @login_required
# def resend_activation_email(request):
#     user = request.user
#     if user.is_active:
#         messages.info(request, 'Your account is already active.')
#         return redirect('login')
#
#     current_site = get_current_site(request)
#     subject = 'Resend Activation Link'
#     message = render_to_string('accounts/account_activation_email.html', {
#         'user': user,
#         'domain': current_site.domain,
#         'uid': urlsafe_base64_encode(force_bytes(user.pk)),
#         'token': default_token_generator.make_token(user),
#     })
#
#     user.email_user(subject, message)
#     messages.success(request, 'A new activation link has been sent to your email.')
#     return redirect('activation_sent')
#
# class CustomLoginView(LoginView):
#     template_name = 'accounts/login.html'
#     authentication_form = EmailLoginForm
#
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import get_user_model, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import SignUpForm, EmailLoginForm, UserProfileForm, DeleteAccountForm
from .models import CustomUser
from projects.models import Project, Donation  # Adjust import based on your project structure


class SignUpView(CreateView):
    model = CustomUser
    form_class = SignUpForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save(commit=False)
        if not user.username:
            user.username = user.email
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        subject = 'Activate your account'
        message = render_to_string('accounts/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': default_token_generator.make_token(user),
        })

        user.email_user(subject, message)
        messages.success(self.request, 'Check your email to activate your account.')
        return redirect('login')


def activate_account(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Your account has been activated. You can now <a href="/accounts/login/">login</a>.')
    else:
        return render(request, 'accounts/activation_invalid.html')


def activation_sent(request):
    return render(request, 'accounts/activation_sent.html')


@login_required
def resend_activation_email(request):
    user = request.user
    if user.is_active:
        messages.info(request, 'Your account is already active.')
        return redirect('login')

    current_site = get_current_site(request)
    subject = 'Resend Activation Link'
    message = render_to_string('accounts/account_activation_email.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': default_token_generator.make_token(user),
    })

    user.email_user(subject, message)
    messages.success(request, 'A new activation link has been sent to your email.')
    return redirect('activation_sent')


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    authentication_form = EmailLoginForm


class ProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'accounts/profile.html'
    context_object_name = 'profile_user'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['projects'] = Project.objects.filter(creator=user)
        context['donations'] = Donation.objects.filter(user=user)
        return context


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = UserProfileForm
    template_name = 'accounts/edit_profile.html'
    success_url = reverse_lazy('profile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Profile updated successfully!')
        return super().form_valid(form)


@login_required
def delete_account_view(request):
    if request.method == 'POST':
        form = DeleteAccountForm(request.user, request.POST)
        if form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, 'Your account has been successfully deleted.')
            return redirect('home')
    else:
        form = DeleteAccountForm(request.user)

    return render(request, 'accounts/confirm_delete.html', {'form': form})

accounts/templates/accounts/account_activation_email.html
<!-- templates/accounts/account_activation_email.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Activate Your Account</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
    <div style="max-width: 600px; margin: auto; background-color: white; border-radius: 8px; padding: 30px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
        <h2 style="color: #333;">Hello {{ user.first_name }},</h2>
        <p style="font-size: 16px; color: #555;">
            Thank you for signing up! Please click the button below to activate your account:
        </p>
        <p style="text-align: center;">
            <a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}"
               style="background-color: #4CAF50; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">
               Activate Account
            </a>
        </p>
        <p style="font-size: 14px; color: #999; margin-top: 30px;">
            This link is valid for 24 hours. If it expires, you can request a new activation link.
        </p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 40px 0;">
        <p style="font-size: 12px; color: #aaa; text-align: center;">
            If you didn’t create an account, you can ignore this email.
        </p>
    </div>
</body>
</html>

accounts/templates/accounts/activation_invalid.html
<h2>Activation Link Invalid</h2>
<p>This activation link is invalid or has expired.</p>
<p><a href="{% url 'resend_activation' %}">Click here to resend the activation email</a></p>

accounts/templates/accounts/activation_sent.html
<h2>Activation Email Sent</h2>
<p>Please check your email and click the link to activate your account.</p>

accounts/templates/accounts/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-danger">
                <div class="card-header bg-danger text-white">
                    <h4 class="mb-0">Delete Account</h4>
                </div>
                <div class="card-body">
                    <div class="alert alert-danger">
                        <strong>Warning!</strong> This action cannot be undone. All your data will be permanently deleted.
                    </div>
                    
                    <form method="post">
                        {% csrf_token %}
                        
                        <div class="mb-4">
                            <p>To confirm deletion, please enter your password:</p>
                            {{ form.password }}
                        </div>
                        
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a href="{% url 'profile' %}" class="btn btn-secondary me-md-2">Cancel</a>
                            <button type="submit" class="btn btn-danger">Delete My Account</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0"><i class="fas fa-user-edit me-2"></i>Edit Profile</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Personal Information -->
                        <div class="mb-4">
                            <h5 class="border-bottom pb-2 mb-3"><i class="fas fa-info-circle me-2"></i>Personal Information</h5>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">First Name</label>
                                    {{ form.first_name }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Last Name</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Mobile Number</label>
                                {{ form.mobile }}
                                <small class="text-muted">Egyptian number (e.g. 01012345678)</small>
                            </div>
                        </div>

                        <!-- Profile Picture -->
                        <div class="mb-4">
                            <h5 class="border-bottom pb-2 mb-3"><i class="fas fa-camera me-2"></i>Profile Picture</h5>
                            <div class="d-flex align-items-center">
                                <div class="position-relative me-4">
                                    <img src="{% if user.profile_picture %}{{ user.profile_picture.url }}{% else %}{% static 'images/default_profile.png' %}{% endif %}"
                                         class="rounded-circle border border-3 border-primary"
                                         width="120"
                                         height="120"
                                         style="object-fit: cover;"
                                         onerror="this.src='{% static 'images/default_profile.png' %}'">
                                    <label for="id_profile_picture" class="position-absolute bottom-0 end-0 bg-white rounded-circle p-2 border border-2 border-primary cursor-pointer">
                                        <i class="fas fa-pencil text-primary"></i>
                                    </label>
                                </div>
                                <div class="flex-grow-1">
                                    <div class="input-group">
                                        <input type="file" class="form-control" id="id_profile_picture" name="profile_picture" accept="image/*">
                                        <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_profile_picture').value=''">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </div>
                                    <small class="text-muted">JPG or PNG, max 2MB</small>
                                </div>
                            </div>
                        </div>

                        <!-- Additional Information -->
                        <div class="mb-4">
                            <h5 class="border-bottom pb-2 mb-3"><i class="fas fa-ellipsis-h me-2"></i>Additional Information</h5>
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Birthdate</label>
                                    {{ form.birthdate }}
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label class="form-label">Country</label>
                                    {{ form.country }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Facebook Profile URL</label>
                                <div class="input-group">
                                    <span class="input-group-text"><i class="fab fa-facebook"></i></span>
                                    {{ form.facebook_profile }}
                                </div>
                            </div>
                        </div>

                        <div class="d-grid gap-2 d-md-flex justify-content-md-end border-top pt-3">
                            <a href="{% url 'profile' %}" class="btn btn-outline-secondary me-md-2">
                                <i class="fas fa-times me-1"></i> Cancel
                            </a>
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save me-1"></i> Save Changes
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// Preview image when selected
document.getElementById('id_profile_picture').addEventListener('change', function(e) {
    const [file] = e.target.files;
    if (file) {
        const reader = new FileReader();
        reader.onload = function(e) {
            document.querySelector('.rounded-circle').src = e.target.result;
        }
        reader.readAsDataURL(file);
    }
});
</script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block link %}
         <a href="{% url 'register' %}">Register</a>
{% endblock %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>

        #log{
 background-color: black;
  color:white;
    padding: 70px;
  border-radius: 0 40px;
  box-shadow: 3px 3px 10px black;
  text-align: center;
  width: 30%;
  margin: 9.3% auto;
}
input{
  width: 90%;
  padding: 10px;
  border: none;
  outline: none;
}
label{
font-size:25px
}
#submit{
width:50%;
  border-radius: 0 30px;
 padding:15px 7px;
 font-size:20px;
 font-weight:bold;
}
#submit:hover{
  background-color: #2670ad;
  color:white
}

    </style>
</head>
<body>

<form method="post" id="log">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="login" id="submit">
    <br>
    <br>
    <p style="color:#2670ad;font-size:22px"><a href="{% url 'signup' %}"  style="color:white;font-size:18px">Register</a> do not have acount?</p>


</form>

</body>
</html>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block link %}
         <a href="{% url 'login' %}">Login</a>
{% endblock %}
{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
    <style>
        #reg{
  background-color: black;
  color:white;
  padding: 70px;
  border-radius: 0 40px;
  box-shadow: 3px 3px 10px black;
  text-align: center;
  width: 30%;
  margin: 3.3% auto;
}
input{
  width: 90%;
  padding: 10px;
  border: none;
  outline: none;
}
label{
font-size:25px
}
#submit{
width:50%;
margin:20px;
  border-radius: 0 30px;
 padding:15px 7px;
 font-size:20px;
 font-weight:bold;
}
#submit:hover{
  background-color: #2670ad;
  color:white
}

    </style>
<body>
<form method="post" id="reg">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="register" id="submit">
    <p style="color:#2670ad;font-size:22px"><a href="{% url 'login' %}"  style="color:white;font-size:18px">Login</a> have acount?</p>

</form>

<div style="color:red">
    {{error}}
</div>
</body>
</html>
{% endblock %}